ALTER TABLE student ALTER COLUMN birthday SET NOT NULL;

ALTER TABLE mark ALTER COLUMN student_id SET NOT NULL;
ALTER TABLE mark ALTER COLUMN subject_id SET NOT NULL;
ALTER TABLE mark ADD CONSTRAINT mark_check CHECK(mark BETWEEN 1 AND 10);

ALTER TABLE subject ADD CONSTRAINT grade_check CHECK(grade BETWEEN 1 AND 10);

ALTER TABLE paymenttype ADD UNIQUE(name);

ALTER TABLE payment ALTER COLUMN type_id BIGINT NOT NULL;
ALTER TABLE payment ALTER COLUMN amount decimal NOT NULL;
ALTER TABLE payment ALTER COLUMN payment_date DateTime NOT NULL;